server:
  port: 8081

spring:
  application:
    name: account-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/ridelink_accounts
      database: ridelink_accounts

  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000         # 24 hours in milliseconds
      refresh-token:
        expiration: 604800000      # 7 days in milliseconds

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    com.ridelink.accountservice: DEBUG
    org.springframework.security: INFO
    org.springframework.data.mongodb: INFO
